- name: Perform a complete update
  yum:
    name: '*'
    state: latest

- name: Enable EPEL repository
  yum:
    name: epel-release
    state: latest

- name: Enable GlusterFS nightly rpms repository
  command: yum-config-manager --add-repo http://artifacts.ci.centos.org/gluster/nightly/master.repo

# required for dependencies
- name: Enable GlusterFS repo
  yum:
    name: centos-release-gluster
    state: latest

- name: Enable Samba nightly rpms repository
  command: yum-config-manager --add-repo http://artifacts.ci.centos.org/gluster/nightly-samba/master/centos/samba-nightly-master.repo

- name: Restart systemd
  command: kill -TERM 1
